#include "libftprintf.h"

int main()
{
	char *s2 = "mohammed";

	// ft_printf(" %d ", 0);
	// ft_printf(" %d ", -1);
	// ft_printf(" %d ", 1);
	// ft_printf(" %d ", 9);
	// ft_printf(" %d ", 10);
	// ft_printf(" %d ", 11);
	// ft_printf(" %d ", 15);
	// ft_printf(" %d ", 16);
	// ft_printf(" %d ", 17);
	// ft_printf(" %d ", 99);
	// ft_printf(" %d ", 100);
	// ft_printf(" %d ", 101);
	// ft_printf(" %d ", -9);
	// ft_printf(" %d ", -10);
	// ft_printf(" %d ", -11);
	// ft_printf(" %d ", -14);
	// ft_printf(" %d ", -15);
	// ft_printf(" %d ", -16);
	// ft_printf(" %d ", -99);
	// ft_printf(" %d ", -100);
	// ft_printf(" %d ", -101);
	// ft_printf(" %d ", INT_MAX);
	// ft_printf(" %d ", INT_MIN);
	// printf("\n%d ", 0);
	// printf("%s", "printf :");
	// printf("%d ", -1);
	// printf("%d ", 1);
	// printf("%d ", 9);
	// printf("%d ", 10);
	// printf("%d ", 11);
	// printf("%d ", 15);
	// printf("%d ", 16);
	// printf("%d ", 17);
	// printf("%d ", 99);
	// printf("%d ", 100);
	// printf("%d ", 101);
	// printf("%d ", -9);
	// printf("%d ", -10);
	// printf("%d ", -11);
	// printf("%d ", -14);
	// printf("%d ", -15);
	// printf("%d ", -16);
	// printf("%d ", -99);
	// printf("%d ", -100);
	// printf("%d ", -101);
	// printf("%d ", INT_MAX);
	// printf("%d ", INT_MIN);
	// ft_printf(" %d ", LONG_MAX);
	// printf(" %d \n", LONG_MAX);
	// ft_printf(" %d ", LONG_MIN);
	// printf(" %d \n", LONG_MIN);
	// ft_printf(" %d ", UINT_MAX);
	// printf(" %d \n", UINT_MAX);
	// ft_printf(" %d ", ULONG_MAX);
	// printf(" %d \n", ULONG_MAX);
	// ft_printf(" %d ", 9223372036854775807LL);
	// printf(" %d \n", 9223372036854775807LL);
	// ft_printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n%d %d %d %d %d %d %d\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);

	// ft_printf("%c", '0');
	// printf("printf: %c\n", '0');
	// ft_printf(" %c ", '0');
	// printf("printf: %c \n", '0');
	// ft_printf(" %c", '0' - 256);
	// printf("printf: %c\n", '0' - 256);
	// ft_printf("%c ", '0' + 256);
	// printf("printf:%c \n", '0' + 256);
	// ft_printf(" %c %c %c ", '0', 0, '1');
	// printf("printf: %c %c %c \n", '0', 0, '1');
	// ft_printf(" %c %c %c ", ' ', ' ', ' ');
	// printf("printf: %c %c %c \n", ' ', ' ', ' ');
	// ft_printf(" %c %c %c ", ' ', ' ', ' ');
	// printf("printf: %c %c %c \n", ' ', ' ', ' ');
	// ft_printf(" %c %c %c ", '1', '2', '3');
	// printf("printf: %c %c %c \n", '1', '2', '3');
	// ft_printf(" %c %c %c ", '2', '1', 0);
	// printf("printf: %c %c %c \n", '2', '1', 0);
	// ft_printf(" %c %c %c ", 0, '1', '2');
	// printf("printf: %c %c %c \n", 0, '1', '2');

	// ft_printf(" %p ", -1);
	// printf(" printf : %p \n", -1);
	// ft_printf(" %p ", 1);
	// printf(" printf : %p \n", 1);
	// ft_printf(" %p ", 15);
	// printf(" printf : %p \n", 15);
	// ft_printf(" %p ", 16);
	// printf(" printf : %p \n", 16);
	// ft_printf(" %p ", 17);
	// printf(" printf : %p \n", 17);
	// ft_printf(" %p %p ", LONG_MIN, LONG_MAX);
	// printf(" printf : %p %p \n", LONG_MIN, LONG_MAX);
	// ft_printf(" %p %p ", INT_MIN, INT_MAX);
	// printf(" printf : %p %p \n", INT_MIN, INT_MAX);
	// ft_printf(" %p %p ", ULONG_MAX, -ULONG_MAX);
	// printf(" printf : %p %p \n", ULONG_MAX, -ULONG_MAX);
	// ft_printf(" %p %p ", 0, 0);
	// printf(" printf : %p %p \n", 0, 0);

	// ft_printf("%s", "");
	// printf(" printf : %s\n", "");
	// ft_printf(" %s", "");
	// printf(" printf :  %s\n", "");
	// ft_printf("%s ", "");
	// printf(" printf : %s\n", "");
	// ft_printf(" %s ", "");
	// printf(" printf :  %s\n", "");
	// ft_printf(" %s ", "-");
	// printf(" printf :  %s\n", "-");
	// ft_printf(" %s %s ", "", "-");
	// printf(" printf :  %s %s\n", "", "-");
	// ft_printf(" %s %s ", " - ", "");
	// printf(" printf :  %s %s\n", " - ", "");
	// ft_printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	// printf(" printf :  %s %s %s %s %s\n", " - ", "", "4", "", s2);
	// ft_printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	// printf(" printf :  %s %s %s %s %s\n", " - ", "", "4", "", "2 ");
	// ft_printf("NULL %s NULL", NULL);
	// printf(" printf :  NULL %s NULL\n", NULL);

	
	// ft_printf(" %i ", 0);
	// ft_printf(" %i ", -1);
	// ft_printf(" %i ", 1);
	// ft_printf(" %i ", 9);
	// ft_printf(" %i ", 10);
	// ft_printf(" %i ", 11);
	// ft_printf(" %i ", 15);
	// ft_printf(" %i ", 16);
	// ft_printf(" %i ", 17);
	// ft_printf(" %i ", 99);
	// ft_printf(" %i ", 100);
	// ft_printf(" %i ", 101);
	// ft_printf(" %i ", -9);
	// ft_printf(" %i ", -10);
	// ft_printf(" %i ", -11);
	// ft_printf(" %i ", -14);
	// ft_printf(" %i ", -15);
	// ft_printf(" %i ", -16);
	// ft_printf(" %i ", -99);
	// ft_printf(" %i ", -100);
	// ft_printf(" %i ", -101);
	// ft_printf(" %i ", INT_MAX);
	// ft_printf(" %i ", INT_MIN);
	// ft_printf(" %i ", LONG_MAX);
	// ft_printf(" %i ", LONG_MIN);
	// ft_printf(" %i ", UINT_MAX);
	// ft_printf(" %i ", ULONG_MAX);
	// ft_printf(" %i ", 9223372036854775807LL);
	// ft_printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n printf: %i \n", 0);
	// printf("printf: %i \n", -1);
	// printf("printf: %i \n", 1);
	// printf("printf: %i \n", 9);
	// printf("printf: %i \n", 10);
	// printf("printf: %i \n", 11);
	// printf("printf: %i \n", 15);
	// printf("printf: %i \n", 16);
	// printf("printf: %i \n", 17);
	// printf("printf: %i \n", 99);
	// printf("printf: %i \n", 100);
	// printf("printf: %i \n", 101);
	// printf("printf: %i \n", -9);
	// printf("printf: %i \n", -10);
	// printf("printf: %i \n", -11);
	// printf("printf: %i \n", -14);
	// printf("printf: %i \n", -15);
	// printf("printf: %i \n", -16);
	// printf("printf: %i \n", -99);
	// printf("printf: %i \n", -100);
	// printf("printf: %i \n", -101);
	// printf("printf: %i \n", INT_MAX);
	// printf("printf: %i \n", INT_MIN);
	// printf("printf: %i \n", LONG_MAX);
	// printf("printf: %i \n", LONG_MIN);
	// printf("printf: %i \n", UINT_MAX);
	// printf("printf: %i \n", ULONG_MAX);
	// printf("printf: %i \n", 9223372036854775807LL);
	// printf("printf: %i %i %i %i %i %i %i\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	
	// ft_printf(" %u ", 0);
	// ft_printf(" %u ", -1);
	// ft_printf(" %u ", 1);
	// ft_printf(" %u ", 9);
	// ft_printf(" %u ", 10);
	// ft_printf(" %u ", 11);
	// ft_printf(" %u ", 15);
	// ft_printf(" %u ", 16);
	// ft_printf(" %u ", 17);
	// ft_printf(" %u ", 99);
	// ft_printf(" %u ", 100);
	// ft_printf(" %u ", 101);
	// ft_printf(" %u ", -9);
	// ft_printf(" %u ", -10);
	// ft_printf(" %u ", -11);
	// ft_printf(" %u ", -14);
	// ft_printf(" %u ", -15);
	// ft_printf(" %u ", -16);
	// ft_printf(" %u ", -99);
	// ft_printf(" %u ", -100);
	// ft_printf(" %u ", -101);
	// ft_printf(" %u ", INT_MAX);
	// printf(" %u \n", INT_MAX);
	// ft_printf(" %u ", INT_MIN);
	// printf(" %u \n", INT_MIN);
	// ft_printf(" %u ", LONG_MAX);
	// printf(" %u \n", LONG_MAX);
	// ft_printf(" %u ", LONG_MIN);
	// printf(" %u \n", LONG_MIN);
	// ft_printf(" %u ", UINT_MAX);
	// printf(" %u \n", UINT_MAX);
	// ft_printf(" %u ", ULONG_MAX);
	// printf(" %u \n", ULONG_MAX);
	// ft_printf(" %u ", 9223372036854775807LL);
	// printf(" %u \n", 9223372036854775807LL);
	// printf("|%u|", -42);
	// ft_printf(" |%u|", -42);
	// ft_printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	
	// ft_printf(" %x ", 0);
	// printf("\n");
	// ft_printf(" %x ", -1);
	// printf("\n");
	// ft_printf(" %x ", 1);
	// printf("\n");
	// ft_printf(" %x ", 9);
	// printf("\n");
	// ft_printf(" %x ", 10);
	// printf("\n");
	// ft_printf(" %x ", 11);
	// printf("\n");
	// ft_printf(" %x ", 15);
	// printf("\n");
	// ft_printf(" %x ", 16);
	// printf("\n");
	// ft_printf(" %x ", 17);
	// printf("\n");
	// ft_printf(" %x ", 99);
	// printf("\n");
	// ft_printf(" %x ", 100);
	// printf("\n");
	// ft_printf(" %x ", 101);
	// printf("\n");
	// ft_printf(" %x ", -9);
	// printf("\n");
	// ft_printf(" %x ", -10);
	// printf("\n");
	// ft_printf(" %x ", -11);
	// printf("\n");
	// ft_printf(" %x ", -14);
	// printf("\n");
	// ft_printf(" %x ", -15);
	// printf("\n");
	// ft_printf(" %x ", -16);
	// printf("\n");
	// ft_printf(" %x ", -99);
	// printf("\n");
	// ft_printf(" %x ", -100);
	// printf("\n");
	// ft_printf(" %x ", -101);
	// printf("\n");
	// ft_printf(" %x ", INT_MAX);
	// printf("\n");
	// ft_printf(" %x ", INT_MIN);
	// printf("\n");
	// ft_printf(" %x ", LONG_MAX);
	// printf("\n");
	// ft_printf(" %x ", LONG_MIN);
	// printf("\n");
	// ft_printf(" %x ", UINT_MAX);
	// printf("\n");
	// ft_printf(" %x ", ULONG_MAX);
	// printf("\n");
	// ft_printf(" %x ", 9223372036854775807LL);
	// printf("\n");
	// ft_printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n");
	// ft_printf(" %x ", 42);
	// printf("\n");
	// ft_printf(" %x ", -42);
	// printf("\n");
	// printf("printf: %x \n", 0);
	// printf("printf: %x \n", -1);
	// printf("printf: %x \n", 1);
	// printf("printf: %x \n", 9);
	// printf("printf: %x \n", 10);
	// printf("printf: %x \n", 11);
	// printf("printf: %x \n", 15);
	// printf("printf: %x \n", 16);
	// printf("printf: %x \n", 17);
	// printf("printf: %x \n", 99);
	// printf("printf: %x \n", 100);
	// printf("printf: %x \n", 101);
	// printf("printf: %x \n", -9);
	// printf("printf: %x \n", -10);
	// printf("printf: %x \n", -11);
	// printf("printf: %x \n", -14);
	// printf("printf: %x \n", -15);
	// printf("printf: %x \n", -16);
	// printf("printf: %x \n", -99);
	// printf("printf: %x \n", -100);
	// printf("printf: %x \n", -101);
	// printf("printf: %x \n", INT_MAX);
	// printf("printf: %x \n", INT_MIN);
	// printf("printf: %x \n", LONG_MAX);
	// printf("printf: %x \n", LONG_MIN);
	// printf("printf: %x \n", UINT_MAX);
	// printf("printf: %x \n", ULONG_MAX);
	// printf("printf: %x \n", 9223372036854775807LL);
	// printf("printf: %x %x %x %x %x %x %x\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("printf: %x \n", 42);
	// printf("printf: %x \n", -42);

	ft_printf("%.dtd", 5);
}
